/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import rs.ac.bg.fon.ps.view.form.util.FormMode;

/**
 *
 * @author ANA
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super("Početna forma");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOdjava = new javax.swing.JButton();
        jmenuBarMain = new javax.swing.JMenuBar();
        jmenuKnjiga = new javax.swing.JMenu();
        jmiNovaKnjiga = new javax.swing.JMenuItem();
        jmiNoviPrimerak = new javax.swing.JMenuItem();
        jmiPrikazKnjiga = new javax.swing.JMenuItem();
        jmenuPozajmica = new javax.swing.JMenu();
        jmiNovaPozajmica = new javax.swing.JMenuItem();
        jmiPregledPozajmica = new javax.swing.JMenuItem();
        jmenuClanovi = new javax.swing.JMenu();
        jmiNoviClan = new javax.swing.JMenuItem();
        jmiPregledClanova = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOdjava.setBackground(new java.awt.Color(255, 0, 0));
        btnOdjava.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnOdjava.setText("Odjavi se");
        btnOdjava.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 0, 0), null, new java.awt.Color(255, 0, 0)));
        btnOdjava.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        jmenuKnjiga.setText("Knjiga");
        jmenuKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuKnjigaActionPerformed(evt);
            }
        });

        jmiNovaKnjiga.setText("Nova knjiga");
        jmiNovaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovaKnjigaActionPerformed(evt);
            }
        });
        jmenuKnjiga.add(jmiNovaKnjiga);

        jmiNoviPrimerak.setText("Novi primerak");
        jmiNoviPrimerak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviPrimerakActionPerformed(evt);
            }
        });
        jmenuKnjiga.add(jmiNoviPrimerak);

        jmiPrikazKnjiga.setText("Prikaz svih knjiga");
        jmiPrikazKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazKnjigaActionPerformed(evt);
            }
        });
        jmenuKnjiga.add(jmiPrikazKnjiga);

        jmenuBarMain.add(jmenuKnjiga);

        jmenuPozajmica.setText("Pozajmica");

        jmiNovaPozajmica.setText("Nova pozajmica");
        jmiNovaPozajmica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovaPozajmicaActionPerformed(evt);
            }
        });
        jmenuPozajmica.add(jmiNovaPozajmica);

        jmiPregledPozajmica.setText("Pregled pozajmica");
        jmenuPozajmica.add(jmiPregledPozajmica);

        jmenuBarMain.add(jmenuPozajmica);

        jmenuClanovi.setText("Članovi");
        jmenuClanovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuClanoviActionPerformed(evt);
            }
        });

        jmiNoviClan.setText("Novi član");
        jmiNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviClanActionPerformed(evt);
            }
        });
        jmenuClanovi.add(jmiNoviClan);

        jmiPregledClanova.setText("Pregled članova");
        jmenuClanovi.add(jmiPregledClanova);

        jmenuBarMain.add(jmenuClanovi);

        setJMenuBar(jmenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNovaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovaKnjigaActionPerformed
//        JDialog frmKnjiga = new FrmKnjiga(this, true, FormMode.FORM_ADD);
//        frmKnjiga.setVisible(true);
    }//GEN-LAST:event_jmiNovaKnjigaActionPerformed

    private void jmenuKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuKnjigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuKnjigaActionPerformed

    private void jmiNoviPrimerakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviPrimerakActionPerformed
//        JFrame frmPrimerak = new FrmPrimerak();
//        frmPrimerak.setVisible(true);
    }//GEN-LAST:event_jmiNoviPrimerakActionPerformed

    private void jmenuClanoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuClanoviActionPerformed

    }//GEN-LAST:event_jmenuClanoviActionPerformed

    private void jmiNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviClanActionPerformed
//        JFrame frmClan = new FrmClan();
//        frmClan.setVisible(true);
    }//GEN-LAST:event_jmiNoviClanActionPerformed

    private void jmiPrikazKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazKnjigaActionPerformed
//        JFrame frm = new FrmPregledKnjiga();
//        frm.setVisible(true);
    }//GEN-LAST:event_jmiPrikazKnjigaActionPerformed

    private void jmiNovaPozajmicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovaPozajmicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiNovaPozajmicaActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOdjavaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava;
    private javax.swing.JMenuBar jmenuBarMain;
    private javax.swing.JMenu jmenuClanovi;
    private javax.swing.JMenu jmenuKnjiga;
    private javax.swing.JMenu jmenuPozajmica;
    private javax.swing.JMenuItem jmiNovaKnjiga;
    private javax.swing.JMenuItem jmiNovaPozajmica;
    private javax.swing.JMenuItem jmiNoviClan;
    private javax.swing.JMenuItem jmiNoviPrimerak;
    private javax.swing.JMenuItem jmiPregledClanova;
    private javax.swing.JMenuItem jmiPregledPozajmica;
    private javax.swing.JMenuItem jmiPrikazKnjiga;
    // End of variables declaration//GEN-END:variables

    public void jmiNovaKnjigaAddActionListener(ActionListener actionListener) {
        jmiNovaKnjiga.addActionListener(actionListener);
    }

    public void jmiPregledSvihKnjigaActionListener(ActionListener actionListener) {
        jmiPrikazKnjiga.addActionListener(actionListener);
    }

    public void jmiPozajmicaNewAddActionListener(ActionListener actionListener) {
        jmiNovaPozajmica.addActionListener(actionListener);
    }

    public void jmiClanNewAddActionListener(ActionListener actionListener) {
        jmiNoviClan.addActionListener(actionListener);
    }

    public void jmiPregledClanovaAddActionListener(ActionListener actionListener) {
        jmiPregledClanova.addActionListener(actionListener);
    }

    public void jmiPregledPozajmicaAddActionListener(ActionListener actionListener) {
        jmiPregledPozajmica.addActionListener(actionListener);
    }

    public void jmiNoviPrimerakNewAddActionListener(ActionListener actionListener) {
        jmiNoviPrimerak.addActionListener(actionListener);
    }

    public JButton getBtnOdjava() {
        return btnOdjava;
    }

    public void addBtnOdlogujSeActionListener(ActionListener actionListener) {
        btnOdjava.addActionListener(actionListener);
    }
    
    
}
